[AppBundler]
app_summary = "Julia Distribution for Science"
windowed = false
overwrite_target = true
selfsign = true

msix.bootstrapper = true
dmg.shallow_signing = true

juliaimg.mainless = true
juliaimg.incremental = true
juliaimg.precompile = true